### ISSUE TITLE
TZData 2017C

### ISSUE THREAD

**Issue by nicegamer7** [Magisk-Modules-Repo/Systemless_TZData#1]
There was an update to TZData that came out about a week ago. It is version 2017C. I just found out today, so I assume it's the same for you.

**Comment by RyanHakurei** [comment]
I am not seeing the update in my sources, can you link to 2017C?

**Comment by nicegamer7** [comment]
https://www.iana.org/time-zones

That is where I found it, just thought I should tell you. Sorry if this is the wrong version or something incompatible, I'm not really sure.

**Comment by RyanHakurei** [comment]
Thanks for the info, I will look into it in about a week when I get home and can test.

**Comment by RyanHakurei** [comment]
I tested it out and it didn't work properly, so I'm going to wait until the source I normally get tzdata from releases, but thank you for letting me know.
