### ISSUE TITLE
2019C

### ISSUE THREAD

**Issue by gjf** [Magisk-Modules-Repo/Systemless_TZData#10]
The latest tzdata has been updated to 2019C: https://www.iana.org/time-zones
I have updated the module to this. It is attached.
Please let me know if you have no time to maintain this beautiful module so I can make a fork.
[Systemless_TZData-2019C.zip](https://github.com/Magisk-Modules-Repo/Systemless_TZData/files/4474353/Systemless_TZData-2019C.zip)

**Comment by RyanHakurei** [comment]
I will most likely push an update today if I don't you're free to submit a PR.

**Comment by gjf** [comment]
You are free to push my file. I'd be happy to help.

**Comment by RyanHakurei** [comment]
c407da4
