### ISSUE TITLE
New update wont install on Magisk 15

### ISSUE THREAD

**Issue by ghost** [Magisk-Modules-Repo/Systemless_TZData#2]
Hello,

While I'm on magisk 15, your module refuses to update with the error "magisk 15+ required"

I've updated other modules with the new template, so I guess there is something wrong with yours.

[install_log_20171227_123611.log](https://github.com/Magisk-Modules-Repo/Systemless_TZData/files/1588842/install_log_20171227_123611.log)

**Comment by osmank3** [comment]
#3 this pull requests solving problem

**Comment by ghost** [comment]
Fixed
