### ISSUE TITLE
V17 does not work on Android 9

### ISSUE THREAD

**Issue by giving-sesame** [Magisk-Modules-Repo/Systemless_TZData#20]
V17 files are mixed up: tzdataN must be tzdataO and vice versa. The same with tz_versionN and tz_versionO. And then tzdataO must be of version 2020a instead of 2020f in order to work normally on Android 9.

**Comment by RyanHakurei** [comment]
Reverted the most recent PR, module should work now.

**Comment by giving-sesame** [comment]
Thank you, it works now.
