### ISSUE TITLE
Already obsolete

### ISSUE THREAD

**Issue by ooonea** [Magisk-Modules-Repo/Systemless_TZData#7]
Unfortunately the update comes only now and is already old. The latest version of tzdata is 2018i https://www.iana.org/time-zones

**Comment by mxalbert1996** [comment]
Just a reminder that you can find the latest tzdata from AOSP repo [here](https://android.googlesource.com/platform/system/timezone/+/master/output_data/iana/tzdata).

**Comment by RyanHakurei** [comment]
[30761ad](https://github.com/Magisk-Modules-Repo/Systemless_TZData/commit/30761ad90e9c27443b889ab785fa7e843e3fe38b)
