### ISSUE TITLE
Check tzdata version

### ISSUE THREAD

**Issue by ooonea** [Magisk-Modules-Repo/Systemless_TZData#9]
How can I check the tzdata version from the command line?

**Comment by RyanHakurei** [comment]
I don't think that is possible on Android. On Linux you'd just check the package version but you can't do that on Android. Timezone Fixer is an app that will tell you your current tzdata version though.

**Comment by ooonea** [comment]
Thank you.  I already knew the application.  I wanted to understand exactly where the data comes from.  Somewhere it must also be readable.

**Comment by supasillyass** [comment]
> 
> 
> How can I check the tzdata version from the command line?

[Locations](https://android.googlesource.com/platform/bionic/+/master/libc/tzcode/bionic.cpp#199):

- `/data/misc/zoneinfo/current/tzdata`
- `/system/usr/share/zoneinfo/tzdata`

Then grab the top of the `tzdata` binary using [strings](https://linux.die.net/man/1/strings)/[head](https://linux.die.net/man/1/head):

~~~
strings /path/to/binary/tzdata 2>dev/null | head -n 1
~~~

Example output: `tzdata2018f`

---

[Re systemless](https://source.android.com/devices/tech/config/timezone-rules#source-code):
> [Android is] configured to be aware of overlay files that may be present in the `/data/misc/zoneinfo/current` directory. **Overlay files are expected to contain improved time zone rules data thereby enabling devices to be updated without changing `/system`.**

My emphasis.

---

Also of possible interest: `/system/bin/tzdatacheck` ([source](https://chromium.googlesource.com/aosp/platform/system/core/+/master/tzdatacheck/tzdatacheck.cpp))

> ~~~
> Usage: tzdatacheck SYSTEM_TZ_DIR DATA_TZ_DIR
>
> Checks whether any timezone update distro in DATA_TZ_DIR is compatible with the
> current Android release and better than or the same as base system timezone rules in
> SYSTEM_TZ_DIR. If the timezone rules in SYSTEM_TZ_DIR are a higher version than the
> one in DATA_TZ_DIR the DATA_TZ_DIR is renamed and then deleted.
> ~~~

**Comment by ooonea** [comment]
I waited so long for an answer, but it was worth it.
